/**
 * RSS Feed Sources for Multiple Languages
 * Rechtlich sichere Musik-News Quellen
 */

export interface FeedSource {
  name: string;
  url: string;
  language: string;
  reliability: "high" | "medium" | "low";
  updateFrequency: "hourly" | "daily" | "weekly";
  musicFocus: "general" | "rock" | "pop" | "electronic" | "indie" | "classical";
}

export const RSS_FEED_SOURCES: Record<string, FeedSource[]> = {
  // Deutsch (de)
  de: [
    {
      name: "Musikexpress – Reviews",
      url: "https://www.musikexpress.de/reviews/feed/",
      language: "de",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Metal Hammer (DE) – Reviews",
      url: "https://www.metal-hammer.de/reviews/feed/",
      language: "de",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Tonspion – Musik",
      url: "https://www.tonspion.de/rubrik/musik/feed",
      language: "de",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "laut.de – Musikmagazin",
      url: "https://feed.laut.de/rss",
      language: "de",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Hiphop.de – Deutschrap & US-Rap",
      url: "https://hiphop.de/rss",
      language: "de",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "SchlagerPlanet – Schlager News",
      url: "https://www.schlagerplanet.com/de/news.rss",
      language: "de",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
  ],

  // Englisch (en)
  en: [
    {
      name: "Rolling Stone – Music",
      url: "https://www.rollingstone.com/music/feed",
      language: "en",
      reliability: "high",
      updateFrequency: "hourly",
      musicFocus: "general",
    },
    {
      name: "Billboard – Music News",
      url: "https://www.billboard.com/feed",
      language: "en",
      reliability: "high",
      updateFrequency: "hourly",
      musicFocus: "pop",
    },
    {
      name: "NPR – Music",
      url: "https://feeds.npr.org/1039/rss.xml",
      language: "en",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "NME – Music News",
      url: "https://www.nme.com/news/music/feed",
      language: "en",
      reliability: "high",
      updateFrequency: "hourly",
      musicFocus: "general",
    },
    {
      name: "Pitchfork – Album Reviews",
      url: "https://pitchfork.com/feed/feed-album-reviews/rss",
      language: "en",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "Spin Magazine",
      url: "https://www.spin.com/feed",
      language: "en",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Stereogum",
      url: "https://www.stereogum.com/feed",
      language: "en",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "The Guardian – Music",
      url: "https://www.theguardian.com/music/rss",
      language: "en",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Französisch (fr)
  fr: [
    {
      name: "Le Monde – Musique",
      url: "https://www.lemonde.fr/musiques/rss_full.xml",
      language: "fr",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Pure Charts (Charts in France)",
      url: "http://www.chartsinfrance.net/actualite/rss.xml",
      language: "fr",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "Les Inrockuptibles – Musique",
      url: "https://www.lesinrocks.com/feeds/feed-musique/",
      language: "fr",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "RFI Musique",
      url: "http://www.rfi.fr/general/rss",
      language: "fr",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rolling Stone (FR) – Musique",
      url: "https://www.rollingstone.fr/feed/",
      language: "fr",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Spanisch (es)
  es: [
    {
      name: "Jenesaispop",
      url: "https://jenesaispop.com/feed",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "Efe Eme",
      url: "https://efeeme.com/feed",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "MondoSonoro",
      url: "https://www.mondosonoro.com/feed/",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "MariskalRock",
      url: "https://mariskalrock.com/index.php/feed/",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Billboard Argentina",
      url: "https://billboard.com.ar/feed/",
      language: "es",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "Rolling Stone (LATAM) – Música",
      url: "https://www.rollingstone.com.mx/feed/",
      language: "es",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Los40 (España) – Lo último",
      url: "https://los40.com/rss/feed.xml",
      language: "es",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "Indie Hoy",
      url: "https://indiehoy.com/feed/",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
  ],

  // Italienisch (it)
  it: [
    {
      name: "Rockol – Ultime News",
      url: "https://www.rockol.it/rss/news.xml",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rockol – Recensioni Album",
      url: "https://www.rockol.it/rss/recensioni.xml",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rolling Stone Italia – Musica",
      url: "https://www.rollingstone.it/feed/",
      language: "it",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rockit",
      url: "https://www.rockit.it/rss",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "TV Sorrisi – Musica",
      url: "https://www.sorrisi.com/rss/musica.xml",
      language: "it",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "Billboard Italia",
      url: "https://www.billboard.it/feed/",
      language: "it",
      reliability: "high",
      updateFrequency: "weekly",
      musicFocus: "pop",
    },
    {
      name: "SoundBlog (Italia)",
      url: "http://www.soundblog.it/rss",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "SentireAscoltare",
      url: "https://sentireascoltare.com/feed/",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
  ],

  // Portugiesisch (pt)
  pt: [
    {
      name: "G1 – Música (Globo)",
      url: "https://g1.globo.com/rss/g1/musica/rss",
      language: "pt",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Whiplash.Net – Rock/Metal",
      url: "https://whiplash.net/feeds/news.xml",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Rolling Stone Brasil – Música",
      url: "https://news.google.com/rss/search?q=site:rollingstone.com.br+Música",
      language: "pt",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Blitz (Portugal)",
      url: "https://expresso.pt/blitz/rss.xml",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Antena 3 – Notícias Música",
      url: "https://antena3.rtp.pt/feed/",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Billboard Brasil",
      url: "https://billboard.com.br/feed/",
      language: "pt",
      reliability: "high",
      updateFrequency: "weekly",
      musicFocus: "pop",
    },
    {
      name: "Vagalume – Notícias de Música",
      url: "https://www.vagalume.com.br/news/index.xml",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "SOM (Portugal)",
      url: "https://expresso.pt/som/rss.xml",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Dänisch (da)
  da: [
    {
      name: "GAFFA (DK)",
      url: "https://gaffa.dk/feed/nyheder",
      language: "da",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Soundvenue – Musik",
      url: "https://soundvenue.com/feed",
      language: "da",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "DR Musik",
      url: "https://www.dr.dk/nyheder/service/feeds/musik",
      language: "da",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Metaladay (DK)",
      url: "https://metaladay.dk/feed/",
      language: "da",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
  ],

  // Niederländisch (nl)
  nl: [
    {
      name: "3voor12 (VPRO)",
      url: "https://3voor12.vpro.nl/rss/nieuws.xml",
      language: "nl",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "OOR Magazine",
      url: "https://oor.nl/feed/",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "NLpop Blog",
      url: "http://www.nlpop.blog/feed/",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "Festivalinfo",
      url: "https://www.festivalinfo.nl/rss/news.xml",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Nieuweplaat.nl",
      url: "https://nieuweplaat.nl/feed/",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Schwedisch (sv)
  sv: [
    {
      name: "GAFFA (SE)",
      url: "https://gaffa.se/rss",
      language: "sv",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Dagens Nyheter – Musik",
      url: "https://www.dn.se/rss/kultur-noje/musik",
      language: "sv",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rocknytt",
      url: "https://www.rocknytt.net/feed",
      language: "sv",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Sveriges Radio P3 – Musik",
      url: "http://api.sr.se/api/rss/channel/164",
      language: "sv",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "HYMN (SE)",
      url: "http://hymn.se/feed/",
      language: "sv",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
  ],

  // Finnisch (fi)
  fi: [
    {
      name: "Soundi",
      url: "https://www.soundi.fi/feed/",
      language: "fi",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Yle Uutiset – Musiikki",
      url: "https://yle.fi/uutiset/rss/18-215082",
      language: "fi",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Inferno (FI)",
      url: "https://www.inferno.fi/feed/",
      language: "fi",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Rumba",
      url: "https://www.rumba.fi/feed/",
      language: "fi",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "HS Kulttuuri – Musiikki",
      url: "https://www.hs.fi/teemat/rss/musiikki.xml",
      language: "fi",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Chinesisch (cn/zh)
  cn: [
    {
      name: "新浪娱乐 – 音乐新闻",
      url: "http://rss.sina.com.cn/ent/music/focus12.xml",
      language: "cn",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "亚洲娱乐网 – 音乐频道",
      url: "http://www.cntvan.com/index.php?m=content&c=rss&catid=46&siteid=1",
      language: "cn",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "亚洲娱乐网 – 音乐业界",
      url: "http://www.cntvan.com/index.php?m=content&c=rss&catid=49&siteid=1",
      language: "cn",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "豆瓣新碟榜 – 华语音乐",
      url: "https://rsshub.app/douban/music/latest/chinese",
      language: "cn",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Blow 吹音乐",
      url: "https://blow.streetvoice.com/feed",
      language: "cn",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "Wooozy",
      url: "http://wooozy.cn/feed",
      language: "cn",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "electronic",
    },
  ],

  // Japanisch (jp)
  jp: [
    {
      name: "音楽ナタリー (Natalie)",
      url: "https://feed.natalie.mu/rss/natalie/news",
      language: "jp",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Musicman (ミュージックマン)",
      url: "https://www.musicman.co.jp/feed/",
      language: "jp",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "amass",
      url: "https://amass.jp/rss/new",
      language: "jp",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
  ],

  // Russisch (ru)
  ru: [
    {
      name: "InterMedia – Музыкальные новости",
      url: "https://www.intermedia.ru/rss/music.xml",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Новости@Mail.ru – Музыка",
      url: "https://news.mail.ru/rss/culture/music/",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "RIA Новости – Музыка",
      url: "https://ria.ru/export/rss2/music/index.xml",
      language: "ru",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Billboard Russia – Новости",
      url: "https://billboard.ru/feed/",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "Rock Kult – Рок-новости",
      url: "https://rockcult.ru/rss",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "NEWSmuz (Новости музыки и шоу-бизнеса)",
      url: "http://feeds.feedburner.com/newsmusic",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Ukrainisch (uk)
  uk: [
    {
      name: "LiRoom (Лірум)",
      url: "https://liroom.com.ua/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Слух (Slukh) – Новини",
      url: "https://slukh.media/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Karabas Live – Новини музики",
      url: "https://karabas.live/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Muzmapa – Музичні статті",
      url: "https://muzmapa.in.ua/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Українське радіо – Музика",
      url: "http://www.nrcu.gov.ua/rss/rss.php?list.41",
      language: "uk",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Neformat",
      url: "https://www.neformat.com.ua/rss",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Notatky",
      url: "https://notatky.com.ua/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
  ],
};

// Musik-Keywords für Content-Filtering
export const MUSIC_KEYWORDS = {
  en: [
    "album",
    "song",
    "band",
    "artist",
    "music",
    "concert",
    "tour",
    "festival",
    "record",
    "single",
    "EP",
    "LP",
    "musician",
    "singer",
    "guitarist",
    "drummer",
    "release",
    "track",
    "recording",
    "studio",
    "vinyl",
    "streaming",
    "spotify",
    "playlist",
    "genre",
    "rock",
    "pop",
    "jazz",
    "classical",
    "electronic",
  ],
  de: [
    "album",
    "song",
    "band",
    "künstler",
    "musik",
    "konzert",
    "tour",
    "festival",
    "platte",
    "single",
    "musiker",
    "sänger",
    "gitarrist",
    "schlagzeuger",
    "veröffentlichung",
    "aufnahme",
    "studio",
    "vinyl",
    "streaming",
    "playlist",
    "genre",
    "rock",
    "pop",
    "jazz",
    "klassik",
    "elektronisch",
  ],
  fr: [
    "album",
    "chanson",
    "groupe",
    "artiste",
    "musique",
    "concert",
    "tournée",
    "festival",
    "disque",
    "single",
    "musicien",
    "chanteur",
    "guitariste",
    "batteur",
    "sortie",
    "enregistrement",
    "studio",
    "vinyle",
    "streaming",
    "playlist",
    "genre",
    "rock",
    "pop",
    "jazz",
    "classique",
    "électronique",
  ],
  es: [
    "álbum",
    "canción",
    "banda",
    "artista",
    "música",
    "concierto",
    "gira",
    "festival",
    "disco",
    "single",
    "músico",
    "cantante",
    "guitarrista",
    "baterista",
    "lanzamiento",
    "grabación",
    "estudio",
    "vinilo",
    "streaming",
    "playlist",
    "género",
    "rock",
    "pop",
    "jazz",
    "clásica",
    "electrónica",
  ],
  it: [
    "album",
    "canzone",
    "band",
    "artista",
    "musica",
    "concerto",
    "tour",
    "festival",
    "disco",
    "single",
    "musicista",
    "cantante",
    "chitarrista",
    "batterista",
    "uscita",
    "registrazione",
    "studio",
    "vinile",
    "streaming",
    "playlist",
    "genere",
    "rock",
    "pop",
    "jazz",
    "classica",
    "elettronica",
  ],
};

// Fallback-Feeds für Sprachen ohne native Feeds
export const FALLBACK_FEEDS = RSS_FEED_SOURCES.en.filter(
  (feed) => feed.reliability === "high" && feed.musicFocus === "general"
);
