/**
 * RSS Feed Sources for Multiple Languages
 * Rechtlich sichere Musik-News Quellen
 */

export interface FeedSource {
  name: string;
  url: string;
  language: string;
  reliability: "high" | "medium" | "low";
  updateFrequency: "hourly" | "daily" | "weekly";
  musicFocus: "general" | "rock" | "pop" | "electronic" | "indie" | "classical";
}

export const RSS_FEED_SOURCES: Record<string, FeedSource[]> = {
  // Deutsch (de)
  de: [
    {
      name: "Musikexpress – Popkultur-Magazin",
      url: "https://www.musikexpress.de/feed/",
      language: "de",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rolling Stone Deutschland",
      url: "https://www.rollingstone.de/feed/",
      language: "de",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Metal Hammer",
      url: "https://www.metal-hammer.de/feed/",
      language: "de",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Visions – Alternative Rock Magazin",
      url: "https://www.visions.de/feed",
      language: "de",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Tonspion – Musik-Blog",
      url: "https://www.tonspion.de/rubrik/musik/feed",
      language: "de",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
  ],

  // Englisch (en)
  en: [
    {
      name: "Rolling Stone – Music",
      url: "https://www.rollingstone.com/music/feed/",
      language: "en",
      reliability: "high",
      updateFrequency: "hourly",
      musicFocus: "general",
    },
    {
      name: "Billboard – Music News",
      url: "https://www.billboard.com/feed/",
      language: "en",
      reliability: "high",
      updateFrequency: "hourly",
      musicFocus: "pop",
    },
    {
      name: "Pitchfork – News",
      url: "https://pitchfork.com/news/feed/",
      language: "en",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "NME – Music News",
      url: "https://www.nme.com/news/music/feed/",
      language: "en",
      reliability: "high",
      updateFrequency: "hourly",
      musicFocus: "general",
    },
    {
      name: "Spin – Music Magazine",
      url: "https://www.spin.com/feed/",
      language: "en",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Französisch (fr)
  fr: [
    {
      name: "Le Monde – Musiques",
      url: "https://www.lemonde.fr/musiques/rss_full.xml",
      language: "fr",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "France Info – Musique",
      url: "https://www.francetvinfo.fr/culture/musique.rss",
      language: "fr",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Libération – Musiques",
      url: "http://www.liberation.fr/interactif/rss/culturerss/musiquesrss/",
      language: "fr",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "RFI Musique – Actualités",
      url: "http://www.rfi.fr/musiquefr/statiques/accueil.xml",
      language: "fr",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Les Inrockuptibles – Musique",
      url: "http://www.lesinrocks.com/feed/",
      language: "fr",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Spanisch (es)
  es: [
    {
      name: "Jenesaispop – Noticias de música",
      url: "https://jenesaispop.com/feed",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "Binaural – Revista musical",
      url: "https://www.binaural.es/feed",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
    {
      name: "Efe Eme – Revista de música",
      url: "https://www.efeeme.com/feed",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Mondo Sonoro – Música indie/rock",
      url: "https://www.mondosonoro.com/feed/mp3",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "MariskalRock – Noticias de rock/metal",
      url: "https://mariskalrock.com/feed/",
      language: "es",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
  ],

  // Italienisch (it)
  it: [
    {
      name: "Rockol – Notizie musicali",
      url: "https://www.rockol.it/rss/news",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rolling Stone Italia – News",
      url: "https://www.rollingstone.it/feed/",
      language: "it",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "ANSA Musica – Kultur/Musik-Nachrichten",
      url: "https://www.ansa.it/sito/notizie/cultura/musica/musica_rss.xml",
      language: "it",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Sentireascoltare – Notizie",
      url: "https://sentireascoltare.com/feed/",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rockit – Musica italiana indie",
      url: "https://www.rockit.it/rss",
      language: "it",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
  ],

  // Portugiesisch (pt)
  pt: [
    {
      name: "G1 Música – Portal de notícias",
      url: "https://g1.globo.com/rss/g1/musica/rss",
      language: "pt",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rolling Stone Brasil – Música",
      url: "https://rollingstone.uol.com.br/feed/",
      language: "pt",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Blitz – Revista de música",
      url: "https://expresso.pt/blitz/rss",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "SIC Notícias – Cultura/Música",
      url: "https://sicnoticias.pt/rss?canal=Cultura",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "UOL Música – Portal",
      url: "https://rss.uol.com.br/feed/musica.xml",
      language: "pt",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Dänisch (da)
  da: [
    {
      name: "GAFFA – Dansk musikmagasin",
      url: "https://gaffa.dk/nyheder/feed/",
      language: "da",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Soundvenue – Musik & kultur",
      url: "https://soundvenue.com/feed",
      language: "da",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "DR Musik – DR Nyheder",
      url: "https://www.dr.dk/nyheder/service/feeds/musik",
      language: "da",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Politiken Musik – Sektion",
      url: "https://politiken.dk/feeds/musik.rss",
      language: "da",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Ekstra Bladet – Musik",
      url: "https://ekstrabladet.dk/rss/kultur/musik",
      language: "da",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Niederländisch (nl)
  nl: [
    {
      name: "3voor12 (VPRO) – Muzieknieuws",
      url: "https://3voor12.vpro.nl/rss/nieuws.xml",
      language: "nl",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "OOR – Muziekmagazine",
      url: "https://oor.nl/feed/",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "NU.nl Muziek – Nieuws",
      url: "https://www.nu.nl/rss/Muziek",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "AD Cultuur – Muziek",
      url: "https://www.ad.nl/cultuur/muziek/rss",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "DutchCharts.nl – Nieuws",
      url: "https://dutchcharts.nl/rss.asp",
      language: "nl",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
  ],

  // Schwedisch (sv)
  sv: [
    {
      name: "GAFFA.se – Musiknyheter",
      url: "https://gaffa.se/nyheter/feed/",
      language: "sv",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rocknytt – Hårdrock nyheter",
      url: "https://www.rocknytt.net/feed",
      language: "sv",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "SVT Nyheter – Kultur",
      url: "https://www.svt.se/kultur/rss.xml",
      language: "sv",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Dagens Nyheter – Musik",
      url: "https://www.dn.se/rss/kultur-noje-musik",
      language: "sv",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Aftonbladet Musik – Nöje",
      url: "https://www.aftonbladet.se/nojesbladet/musik/rss",
      language: "sv",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Finnisch (fi)
  fi: [
    {
      name: "Soundi – Musiikkilehti",
      url: "https://www.soundi.fi/feed/",
      language: "fi",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Rumba – Uutiset",
      url: "https://www.rumba.fi/feed/",
      language: "fi",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Yle Uutiset – Musiikki",
      url: "https://yle.fi/aihe/rss/uutiset/musiikki.rss",
      language: "fi",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Helsingin Sanomat – Kulttuuri",
      url: "https://www.hs.fi/rss/kulttuuri/musiikki.xml",
      language: "fi",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Soundi – Uutiset",
      url: "https://www.soundi.fi/kategoriat/uutiset/feed/",
      language: "fi",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],

  // Chinesisch (cn/zh)
  cn: [
    {
      name: "新浪娱乐 – 音乐新闻",
      url: "http://rss.sina.com.cn/ent/music/focus12.xml",
      language: "cn",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "亚洲娱乐网 – 音乐频道",
      url: "http://www.cntvan.com/index.php?m=content&c=rss&catid=46&siteid=1",
      language: "cn",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "亚洲娱乐网 – 音乐业界",
      url: "http://www.cntvan.com/index.php?m=content&c=rss&catid=49&siteid=1",
      language: "cn",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "豆瓣新碟榜 – 华语音乐",
      url: "https://rsshub.app/douban/music/latest/chinese",
      language: "cn",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Blow 吹音乐 – 台湾独立音乐",
      url: "https://blow.streetvoice.com/feed",
      language: "cn",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "indie",
    },
  ],

  // Japanisch (jp)
  jp: [
    {
      name: "音楽ナタリー – Ongaku Natalie",
      url: "http://feed.natalie.mu/rss/natalie/news",
      language: "jp",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "BARKS Japan – 音楽ニュース",
      url: "http://www.barks.jp/about/?m=rss",
      language: "jp",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Musicman – 音楽産業誌",
      url: "https://www.musicman.co.jp/feed/",
      language: "jp",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "amass Japan – ロック・ポップ",
      url: "https://amass.jp/rss/new",
      language: "jp",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
    {
      name: "Oricon News – 音楽",
      url: "https://www.oricon.co.jp/rss/music.xml",
      language: "jp",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
  ],

  // Russisch (ru)
  ru: [
    {
      name: "InterMedia – Музыкальные новости",
      url: "https://www.intermedia.ru/rss/music.xml",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Новости@Mail.ru – Музыка",
      url: "https://news.mail.ru/rss/culture/music/",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "RIA Новости – Музыка",
      url: "https://ria.ru/export/rss2/music/index.xml",
      language: "ru",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Billboard Russia – Новости",
      url: "https://billboard.ru/feed/",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "pop",
    },
    {
      name: "Rock Kult – Рок-новости",
      url: "https://rockcult.ru/rss",
      language: "ru",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "rock",
    },
  ],

  // Ukrainisch (uk)
  uk: [
    {
      name: "LiRoom – Музичні новини",
      url: "https://liroom.com.ua/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Слух (Slukh) – Новини",
      url: "https://slukh.media/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Karabas Live – Новини музики",
      url: "https://karabas.live/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Muzmapa – Музичні статті",
      url: "https://muzmapa.in.ua/feed/",
      language: "uk",
      reliability: "medium",
      updateFrequency: "daily",
      musicFocus: "general",
    },
    {
      name: "Українське радіо – Музика",
      url: "http://www.nrcu.gov.ua/rss/rss.php?list.41",
      language: "uk",
      reliability: "high",
      updateFrequency: "daily",
      musicFocus: "general",
    },
  ],
};

// Musik-Keywords für Content-Filtering
export const MUSIC_KEYWORDS = {
  en: [
    "album",
    "song",
    "band",
    "artist",
    "music",
    "concert",
    "tour",
    "festival",
    "record",
    "single",
    "EP",
    "LP",
    "musician",
    "singer",
    "guitarist",
    "drummer",
    "release",
    "track",
    "recording",
    "studio",
    "vinyl",
    "streaming",
    "spotify",
    "playlist",
    "genre",
    "rock",
    "pop",
    "jazz",
    "classical",
    "electronic",
  ],
  de: [
    "album",
    "song",
    "band",
    "künstler",
    "musik",
    "konzert",
    "tour",
    "festival",
    "platte",
    "single",
    "musiker",
    "sänger",
    "gitarrist",
    "schlagzeuger",
    "veröffentlichung",
    "aufnahme",
    "studio",
    "vinyl",
    "streaming",
    "playlist",
    "genre",
    "rock",
    "pop",
    "jazz",
    "klassik",
    "elektronisch",
  ],
  fr: [
    "album",
    "chanson",
    "groupe",
    "artiste",
    "musique",
    "concert",
    "tournée",
    "festival",
    "disque",
    "single",
    "musicien",
    "chanteur",
    "guitariste",
    "batteur",
    "sortie",
    "enregistrement",
    "studio",
    "vinyle",
    "streaming",
    "playlist",
    "genre",
    "rock",
    "pop",
    "jazz",
    "classique",
    "électronique",
  ],
  es: [
    "álbum",
    "canción",
    "banda",
    "artista",
    "música",
    "concierto",
    "gira",
    "festival",
    "disco",
    "single",
    "músico",
    "cantante",
    "guitarrista",
    "baterista",
    "lanzamiento",
    "grabación",
    "estudio",
    "vinilo",
    "streaming",
    "playlist",
    "género",
    "rock",
    "pop",
    "jazz",
    "clásica",
    "electrónica",
  ],
  it: [
    "album",
    "canzone",
    "band",
    "artista",
    "musica",
    "concerto",
    "tour",
    "festival",
    "disco",
    "single",
    "musicista",
    "cantante",
    "chitarrista",
    "batterista",
    "uscita",
    "registrazione",
    "studio",
    "vinile",
    "streaming",
    "playlist",
    "genere",
    "rock",
    "pop",
    "jazz",
    "classica",
    "elettronica",
  ],
};

// Fallback-Feeds für Sprachen ohne native Feeds
export const FALLBACK_FEEDS = RSS_FEED_SOURCES.en.filter(
  (feed) => feed.reliability === "high" && feed.musicFocus === "general"
);
